# Étape 1 : build avec Maven wrapper depuis le dossier demo
FROM eclipse-temurin:21-jdk-alpine as build
WORKDIR /app
COPY demo/ ./demo/
WORKDIR /app/demo
RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

# Étape 2 : image d'exécution avec JRE seulement
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/demo/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
