# Build React app using a smaller, more secure image
FROM node:20-slim AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build

# Serve with secure Nginx image
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
