# Étape 1 : Build statique avec Next.js (output: 'export')
FROM node:20-slim AS build
WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
RUN npm run build

# Étape 2 : Serveur Nginx
FROM nginx:alpine
COPY --from=build /app/out /usr/share/nginx/html
EXPOSE 80
